services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7069:7069"
    environment:
      - DB_HOST=${DB_HOST}  # IP ou nome do domínio do servidor
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB=${DB}

  db:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_PASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}  
    ports:
      - "13331:13331"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: