services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB=${DB_PASSWORD}

    depends_on:
      - db

  db:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_PASS}
      MYSQL_DATABASE: ${LOCAL_DB}
      MYSQL_USER: ${LOCAL_USER}
      MYSQL_PASSWORD: ${LOCAL_PASS}  
    ports:
      - "13331:13331"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
